<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;    //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;        //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\starter\Starter as Starter;                    //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ApiKey as ApiKey;                   //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim

    
    // Get module information (include cache and for public user)
    $app->map(['GET','OPTIONS'],'/starter/get/info/', function (Request $request, Response $response) {
        $s = new Starter($this->db);
        $body = $response->getBody();
        $response = $this->cache->withEtag($response, $this->etag2hour.'-'.trim($_SERVER['REQUEST_URI'],'/'));
        $body->write($s->viewInfo());
        return classes\Cors::modify($response,$body,200,$request);
    })->add(new ApiKey);


    /**
     * Create your app router below here (this is only an example)
     */
    $app->get('/starter/example/test', function(Request $request, Response $response){
        $body = $response->getBody();
        $body->write('{"result":"This is just test the router."}');
        return classes\Cors::modify($response,$body,200);
    });